---
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    openshift.io/display-name: "Red Hat Connectivity Link Operator"
  labels:
    openshift.io/cluster-monitoring: 'true'
  name: redhat-connectivity-link-operator
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: connectivity-link-operator
  namespace: redhat-connectivity-link-operator
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: kuadrant-operator
  namespace: redhat-connectivity-link-operator
spec:
  channel: stable
  name: kuadrant-operator
  source: community-operators
  sourceNamespace: openshift-marketplace
  installPlanApproval: Automatic
