---
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    openshift.io/display-name: "OpenShift Custom Metrics Autoscaler Operator"
  labels:
    openshift.io/cluster-monitoring: 'true'
  name: openshift-keda
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: openshift-custom-metrics-autoscaler-operator
  namespace: openshift-keda
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: openshift-custom-metrics-autoscaler-operator
  namespace: openshift-keda
spec:
  channel: stable
  name: openshift-custom-metrics-autoscaler-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  installPlanApproval: Automatic
