---
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    openshift.io/display-name: "Kueue Operator"
  labels:
    openshift.io/cluster-monitoring: 'true'
  name: openshift-kueue-operator
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: kueue-operator
  namespace: openshift-kueue-operator
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: kueue-operator
  namespace: openshift-kueue-operator
spec:
  channel: stable-v1.2
  name: kueue-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  installPlanApproval: Automatic
